version: 2
jobs:
  build-search-images:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "image-search/package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: cd image-search && yarn install && cd ..
      - save_cache:
          paths:
            - image-search/node_modules
          key: v1-dependencies-{{ checksum "image-search/package.json" }}
      - run:
          name: Test run
          command: cd image-search && node index.js test output.txt && test -e output.txt
  build-download-image:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-java-{{ checksum "download-image/pom.xml" }}
      - run: cd download-image && mvn dependency:go-offline && cd ..
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-java-{{ checksum "download-image/pom.xml" }}
      - run:
          name: Build
          command: cd download-image && ./build.sh && cd ..
      - run:
          name: Test run
          command: cd download-image && ./run.sh && test -e output.jpg
workflows:
  version: 2
  build:
    jobs:
      - build-search-images
      - build-download-image
