version: 2
jobs:
  build-search-images:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "image-search/package.json" }}
          - v1-dependencies-
      - run: |
        cd image-search
        yarn install
        cd ..
      - save_cache:
          paths:
            - image-search/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: |
        cd image-search
        node index.js test output.txt
        test -e output.txt

workflows:
  version: 2
  build:
    jobs:
      - build
