version: 2
references:
  restore_repo: &restore_repo
    restore_cache:
      name: Restore checked out code
      keys:
        - v1-code-{{ .Branch }}-{{ .Revision }}
        - v1-code-{{ .Branch }}-
        - v1-code

jobs:
  checkout_code:
    docker:
      - image: circleci/node:10.4
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-code-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .

  build_search_images:
    docker:
      - image: node:10-alpine
    steps:
      - *restore_repo
      - attach_workspace:
          at: /home/circleci/project
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "image-search/package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: cd image-search && yarn install && cd ..
      - save_cache:
          paths:
            - image-search/node_modules
          key: v1-dependencies-{{ checksum "image-search/package.json" }}
      - run:
          name: Test run
          command: cd image-search && node index.js test output.txt && test -e output.txt
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - search-images/output.txt

  build_download_image:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - setup_remote_docker
      - restore_cache:
          key: v1-dependencies-java-{{ checksum "download-image/pom.xml" }}
      - run: cd download-image && mvn dependency:go-offline && cd ..
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-java-{{ checksum "download-image/pom.xml" }}
      - run:
          name: Build
          command: cd download-image && ./build.sh && cd ..
      - run:
          name: Test run
          command: cd download-image && ./test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build_search_images:
          requires:
            - checkout_code
      - build_download_image:
          requires:
            - build_search_images
