version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run: |
        npm install
        node index.js test output.txt
        test -e output.txt

workflows:
  version: 2
  build:
    jobs:
      - build
